### PR TITLE
Allow use of secret files.

### LINKED ISSUE #3: Move secrets to secrets vs env-vars
This should be a small change.

Would be good to add a flag so that it can even run on a public OpenFaaS Cloud instance.

### PR DESCRIPTION
**Pull request by bweston92**
This PR will add the ability to use secrets instead of having environment variables contain secret information.

For example `get_config("consumer_key")` will first lookup to see if `consumer_key` is in the environment if so then return it.

Otherwise if key `consumer_key_file` exists we will read the files content and return it.

Otherwise we will search `/run/secrets/consumer_key` and `/var/openfaas/secrets/consumer_key` and if any of them exist we will return the files content.

If all these fail then the second argument to `get_config` is returned and by default that is `None`

p.s I'm not a Python developer so this may be way off.

fixes #3

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @bweston92 please can you sign off this commit?

How have you tested the change?

Alex

**Comment by bweston92** [comment]
Sorry I can write tests if you want but I don't know OpenFaas to test it.

**Comment by alexellis** [comment]
Thanks for signing-off the commit. FYI this project is licensed MIT and follows the OpenFaaS contribution process.

**Comment by alexellis** [comment]
Should be relatively straight-forward to test. It will help your PR get merged as I don't have time to do this any time soon (and I can't put untested code onto the server, how do we know it works?).

Alex

**Comment by alexellis** [comment]
Please ask on Slack if you need help getting a Twitter API token etc.

**Comment by alexellis** [comment]
Testing:

* Deploy OpenFaaS
* Setup a testing Patreon page
* Setup a Twitter account and get your access key / secret

* Create your secrets
* Build and deploy the code from your fork

Now trigger a test event from Patreon and check that the Tweet appears on the test account.

**Comment by bweston92** [comment]
closing until I can find time to test

**Pull request closed without merging**
