### PR TITLE
Update handler.py

### LINKED ISSUE #8: Add a link to the Patreon page in the thank you tweet.
We should add a link to the Patreon page in the thank you tweet. Currently people have to search for the URL if they see the tweet.

### PR DESCRIPTION
**Pull request by ghost**
Add link to Patreon page within the thank you tweet

Fixes #8

Signed-off-by: Sal DiStefano <sal@saldistefano.com>

### CODE REVIEW

**Review by alexellis — COMMENTED** [review]
Looks good. Are we in any danger of exceeding the max length of a tweet?

**Comment by ghost** [comment]
With the added link to the Patreon site, using the last tweet as an estimate, it was only at 122 characters. As of last year, Twitter allows 280 characters per Tweet, so I think we're ok. 

We could always check the length of the Tweet string and validate before trying to send, and modify if necessary.

**Comment by rajatjindal** [comment]
ping @alexellis to merge this.

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Let's please validate before we add the final part of the URL.

**Comment by alexellis** [comment]
Having a clear-up on GitHub issues / PRs over 1 month old. Let's revisit as necessary. Thank you for the PR.

**Pull request closed without merging**
